- name: uninstall scaleio
  hosts: all
  tasks:
  - name: uninstall package
    environment:
      I_AM_SURE: 1
    package: name="{{ item }}" state="absent"
    with_items:
     - EMC-ScaleIO-lia
     - EMC-ScaleIO-sds
     - EMC-ScaleIO-mdm
     - EMC-ScaleIO-callhome
     - EMC-ScaleIO-sdc
     - EMC-ScaleIO-tb
     - EMC-ScaleIO-gateway
     - EMC-ScaleIO-gui
